name: Mi primera integraci贸n continua

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: empaquetado
              run: echo "Empaquetando el proyecto"

    test:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: pruebas
              run: echo "Ejecutando los tests"

    controlar_calidad:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: calidad
              run: echo "Controlando la calidad del c贸digo"

    deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: despliegue
              run: echo "Desplegando la aplicaci贸n"

            - name: notificaci贸n
              run: echo "Notificando el despliegue"
              if: always()
    
