name: Mi primera integración continua

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Descargar Repositorio
              uses: actions/checkout@v2
            - name: Instalar JDK 11
              uses: actions/setup-java@v2
              with:
                distribution: 'adopt'
                java-version: '11'
            - name: Construir con maven
              run: |
                mvn clean package -DskipTests
                ls ./target
            - name: Guardar paquete .jar para después desplegar
              uses: actions/upload-artifact@v4
              with:
                name: moviecards-java
                path: "${{ github.workspace }}/target/*.jar"
            - name: Verificar contenido de la carpeta target
              run: ls -la ${{ github.workspace }}/target

    test:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Descargar repositorio
              uses: actions/checkout@v2
            - name: Instalar JDK 11
              uses: actions/setup-java@v2
              with:
                java-version: "11"
                distribution: "adopt"
            - name: Instalar Chrome y ChromeDriver para pruebas end to end
              run: |
                wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
                sudo dpkg -i google-chrome-stable_current_amd64.deb
                sudo apt --fix-broken install -y 
                CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
                curl -L -o chromedriver.zip https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
                unzip chromedriver.zip
                chmod +x chromedriver
                sudo mv chromedriver /usr/local/bin/
            - name: Ejecutar la aplicación para pruebas end to end
              run: mvn spring-boot:run & sleep 60
            - name: Ejecutar las pruebas unitarias, de integración y end to end
              run: mvn clean verify

    qa:
        needs: build
        runs-on: self-hosted
        continue-on-error: true
        steps:
          - name: Descargar repositorio
            uses: actions/checkout@v2
          - name: Instalar JDK 11
            uses: actions/setup-java@v4
            with:
              java-version: "11"
              distribution: "temurin"
              architecture: "aarch64"
          - name: Construir con Maven
            run: mvn clean package -DskipTests
          - name: Revisar la calidad con Sonarqube
            run: |
              mvn sonar:sonar -Dsonar.host.url=http://localhost:9000 -Dsonar.qualitygate.wait=true -Dsonar.login=admin -Dsonar.password=admin1

    deploy:
        needs:  qa
        runs-on: ubuntu-latest
        if: github.ref=='refs/heads/main'
        environment:
          name: 'Production'
          url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
        steps:
            - name: despliegue
              uses: actions/download-artifact@v4
              with:
                name: moviecards-java
            - name: Aprobación manual
              uses: trstringer/manual-approval@v1
              with:
                secret: ${{ secrets.TOKEN }}
                approvers: victor-herguedas
            - name: Deploy to Azure Web App
              id: deploy-to-webapp
              uses: azure/webapps-deploy@v3
              with:
                app-name: 'moviecars-herguedas'
                slot-name: 'Production'
                publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_5FDD92D60C374B289B2D4063A40E96A9 }}
                package: '*.jar'

